### ISSUE TITLE
typescript doesnt seem to like qwik wrap balancer

### ISSUE THREAD

**Issue by LazyClicks** [harshmangalam/qwik-wrap-balancer#1]
Could not find a declaration file for module 'qwikjs-wrap-balancer'. 'd:/Web projects/ibnalhaythem-website/node_modules/qwikjs-wrap-balancer/lib/index.qwik.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/qwikjs-wrap-balancer` if it exists or add a new declaration (.d.ts) file containing `declare module 'qwikjs-wrap-balancer';`

**Comment by harshmangalam** [comment]
Thanks @LazyClicks this issues resolved.
